// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ariwoewhdxznmtgrebcw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyaXdvZXdoZHh6bm10Z3JlYmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA4NjU2NjYsImV4cCI6MjA5NjQ0MTY2Nn0.j8zAe65s0_zvgx3a3UnAaTJ29aXWHStU8MRBZXennxk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});